export const SH_TW_THEME = Symbol('sh-tw-theme')
export const SH_TW_COMPONENTS = Symbol('sh-tw-components')
export const SH_DIALOG_CONTEXT = Symbol('sh-dialog-context')
export const SH_TW_POPUPS = Symbol('sh-tw-popups')
export const SH_POPUP_CONTEXT = Symbol('sh-popup-context')
